### ISSUE TITLE
Not overwriting KeBugCheck only overwriting KeBugCheckEx

### ISSUE THREAD

**Issue by LinuxMilanGithub** [NSG650/NoMoreBugCheck#5]
Some processes like ntoskrnl.exe call [KeBugCheck (Microsoft Learn)](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntddk/nf-ntddk-kebugcheck) instead of [KeBugCheckEx (Microsoft Learn)](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-kebugcheckex) when they have an unrecoverable inconsistency that would corrupt the system/memory etc. if the caller continued to run. The KeBugCheck function is defined in ntddk.h while KeBugCheckEx is defined in wdm.h, ntddk.h and ntifs.h. It even has nearly the same functionality as KeBugCheckEx. It just does not have BugCheckParameters. So why dont you overwrite it too? And why do you pause the thread that caused the event to happen? Why dont you ignore the function call or terminate the thread so the process isnt stuck in an exting mode?

**Comment by LinuxMilanGithub** [comment]
Here is the code I wrote. Sorry that the comments are in German, Im german. (I DONT KNOW IF ITS FUNCTIONAL because I dont have the build tools for it): [Code on paste.gg](https://paste.gg/p/anonymous/ea3019d43ea5482ea1ba95e15a1776af) Could you build the code and send it to me or something? Thank you a lot!

**Comment by NSG650** [comment]
Hi there!

`KeBugCheck` is in fact a wrapper around `KeBugCheckEx` which is why I only hooked `KeBugCheckEx`. This can be seen in disassemblies or projects like ReactOS. There is no need to hook `KeBugCheck`. 

Thank you for helping out though!

**Comment by LinuxMilanGithub** [comment]
Thanks for that but why do you pause the thread that caused the bugcheck?

**Comment by NSG650** [comment]
The calling thread wouldnt continue since a bug check is called when system execution cant continue. So the calling thread is paused indefinitely.

**Comment by LinuxMilanGithub** [comment]
Thank you for your support! I closed this as completed.
